#!/usr/bin/env bash
# P9.6 — QA orchestrator.
#
# Runs probe_pages + verify_facts + check_links and writes a consolidated
# Markdown report at docs/qa/qa-report-YYYY-MM-DD.md with PASS/FAIL per
# dimension. Does NOT spin up the dev/static server — assumes one is
# already listening on $PORT (default 3000).
#
# Usage:
#   python3 -m http.server -d apps/web/out 3000 &
#   ./scripts/qa/run_all.sh
#   kill %1
#
# Override port: PORT=4000 ./scripts/qa/run_all.sh

set -uo pipefail

PORT="${PORT:-3000}"
export PORT
REPO="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO"

DATE="$(date +%Y-%m-%d)"
REPORT="docs/qa/qa-report-${DATE}.md"
mkdir -p docs/qa

PY="${PY:-/private/tmp/herd_venv/bin/python}"
if [ ! -x "$PY" ]; then PY="$(command -v python3 || command -v python)"; fi

# Initialise the report.
{
  echo "# QA Report — ${DATE}"
  echo ""
  echo "Generated by \`scripts/qa/run_all.sh\` against \`localhost:${PORT}\`."
  echo ""
  echo "## Automated dimensions"
  echo ""
} > "$REPORT"

overall=0

# --- 1. probe_pages -----------------------------------------------------------
echo "[run_all] 1/4 probe_pages.js"
LOG1=/tmp/qa_probe.log
if node scripts/qa/probe_pages.js > "$LOG1" 2>&1; then
  status1="PASS"
else
  status1="FAIL"
  overall=1
fi
{
  echo "### Dim 1 — Page probe (errors / overflow / screenshots) — ${status1}"
  echo ""
  echo '```'
  tail -50 "$LOG1"
  echo '```'
  echo ""
  if [ -s qa-probe-report.json ]; then
    echo "Full report: \`qa-probe-report.json\`. Screenshots: \`qa-screens/\`."
    echo ""
  fi
} >> "$REPORT"

# --- 2. verify_facts ----------------------------------------------------------
echo "[run_all] 2/4 verify_facts.py"
LOG2=/tmp/qa_facts.log
if "$PY" scripts/qa/verify_facts.py > "$LOG2" 2>&1; then
  status2="PASS"
else
  status2="FAIL"
  overall=1
fi
{
  echo "### Dim 2 — Fact verification (parquet ↔ expected) — ${status2}"
  echo ""
  echo '```'
  cat "$LOG2"
  echo '```'
  echo ""
} >> "$REPORT"

# --- 3. check_links -----------------------------------------------------------
echo "[run_all] 3/4 check_links.js"
LOG3=/tmp/qa_links.log
if node scripts/qa/check_links.js > "$LOG3" 2>&1; then
  status3="PASS"
else
  status3="FAIL"
  overall=1
fi
{
  echo "### Dim 3 — Link integrity (no 4xx/5xx) — ${status3}"
  echo ""
  echo '```'
  cat "$LOG3"
  echo '```'
  echo ""
} >> "$REPORT"

# --- 4. axe_audit (a11y) ------------------------------------------------------
echo "[run_all] 4/4 axe_audit.js"
LOG4=/tmp/qa_axe.log
if [ -f scripts/qa/axe_audit.js ]; then
  if node scripts/qa/axe_audit.js > "$LOG4" 2>&1; then
    status4="PASS"
  else
    status4="FAIL"
    overall=1
  fi
  {
    echo "### Dim 4 — Accessibility (axe-core serious/critical) — ${status4}"
    echo ""
    echo '```'
    cat "$LOG4"
    echo '```'
    echo ""
  } >> "$REPORT"
else
  {
    echo "### Dim 4 — Accessibility (axe-core) — GAP"
    echo ""
    echo "\`scripts/qa/axe_audit.js\` not present; install with P9.7."
    echo ""
  } >> "$REPORT"
fi

# --- 5. Lighthouse (optional — documented gap if not installed) --------------
echo "[run_all] (5) lighthouse.sh"
LOG5=/tmp/qa_lh.log
if command -v lighthouse >/dev/null 2>&1; then
  if bash scripts/qa/lighthouse.sh > "$LOG5" 2>&1; then
    status5="PASS"
  else
    status5="FAIL"
  fi
  {
    echo "### Dim 5 — Lighthouse mobile audit — ${status5}"
    echo ""
    echo "Reports in \`qa-lighthouse/\`. Summary tail:"
    echo ""
    echo '```'
    tail -20 "$LOG5"
    echo '```'
    echo ""
  } >> "$REPORT"
else
  {
    echo "### Dim 5 — Lighthouse mobile audit — GAP"
    echo ""
    echo "Lighthouse is not installed globally on this machine. To run it:"
    echo ""
    echo "    npm install -g lighthouse"
    echo "    ./scripts/qa/lighthouse.sh"
    echo ""
    echo "Documented as a gap — not blocking deploy."
    echo ""
  } >> "$REPORT"
fi

# --- Manual dimensions placeholder -------------------------------------------
{
  echo "## Manual dimensions"
  echo ""
  echo "These complement the automated dims and must be recorded by the operator."
  echo ""
  echo "| # | Dim | Verdict | Notes |"
  echo "| -:|:----|:--------|:------|"
  echo "| 6  | Dark mode parity | _TBD_ | screenshot light vs dark per route |"
  echo "| 7  | Colorblind safety (DevTools deuteranopia/protanopia/tritanopia) | _TBD_ |  |"
  echo "| 8  | Cross-browser (Chrome / Safari / Firefox latest) | _TBD_ |  |"
  echo "| 9  | Bundle size (JS chunks ≤ 250KB gz; parquet < 50MB) | _TBD_ |  |"
  echo "| 10 | Parquet load time on Slow 4G (/universities/[sk] ≤ 4s; /national ≤ 5s) | _TBD_ |  |"
  echo "| 11 | Tabular-numerals alignment | _TBD_ |  |"
  echo "| 12 | Annotation correctness (sample 5 unis vs raw data) | _TBD_ |  |"
  echo "| 13 | Edge cases (5 specific profile shapes) | _TBD_ |  |"
  echo "| 14 | Search & filter on /universities | _TBD_ |  |"
  echo "| 15 | Methodology ↔ chart source-line consistency | _TBD_ |  |"
  echo ""
} >> "$REPORT"

{
  echo "## Summary"
  echo ""
  echo "| Dim | Result |"
  echo "| -:|:-------|"
  echo "| 1 — Page probe | ${status1:-?} |"
  echo "| 2 — Fact verification | ${status2:-?} |"
  echo "| 3 — Link integrity | ${status3:-?} |"
  echo "| 4 — A11y (axe-core) | ${status4:-?} |"
  echo "| 5 — Lighthouse | $([ -n "${status5:-}" ] && echo "${status5}" || echo "GAP") |"
  echo ""
} >> "$REPORT"

echo "[run_all] Report: $REPORT"
exit "$overall"
